version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: genieacs-mongodb
    restart: unless-stopped
    volumes:
      - ./db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=genieacs
      - MONGO_INITDB_ROOT_PASSWORD=genieacs
      - MONGO_INITDB_DATABASE=genieacs
    command: ["--auth", "--wiredTigerCacheSizeGB=1"]

  genieacs:
    build:
      context: .
      args:
        - GENIEACS_VERSION=v1.2.13
    container_name: genieacs
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "7547:7547"  # CWMP
      - "7557:7557"  # FS
      - "7567:7567"  # NBI
      - "3000:3000"  # UI
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://genieacs:genieacs@mongo:27017/genieacs?authSource=admin
      - GENIEACS_UI_JWT_SECRET=${GENIEACS_UI_JWT_SECRET:-change-this-in-production}
      - GENIEACS_UI_INITIAL_USER=admin
      - GENIEACS_UI_INITIAL_PASSWORD=admin
      - GENIEACS_EXT_DIR=/opt/genieacs/ext
      - INIT_DB=true
    volumes:
      - ./config:/opt/genieacs/config
      - ./ext:/opt/genieacs/ext
      - ./logs:/var/log/genieacs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    command: >
      /bin/sh -c "
      /usr/bin/supervisord -c /etc/supervisor/conf.d/genieacs.conf
      "

# Create required directories if they don't exist
volumes:
  - db
  - ext
  - logs
